window.addEventListener("load",function(){var a=document.getElementsByClassName("banner")[0],k=document.getElementsByClassName("fix")[0],d=document.getElementsByClassName("e_nav")[0],c=document.querySelectorAll(".nav li"),f=document.querySelectorAll("a");a&&carousel(a);imgAsynLoad("img[oper='asyn']");if(c.length)for(a=0;a<c.length;a++)(function(a){var b=a.querySelector("div");b&&(a.height=b.offsetHeight,b.style.height="0",a.addEventListener("mouseenter",function(){b.style.height=this.height+"px";
b.style.opacity="1"},!1),a.addEventListener("mouseleave",function(){b.style.height="0";b.style.opacity="0"},!1),a.addEventListener("click",function(){var a=document.querySelector("#replace");a.setAttribute("href","#"+this.getAttribute("link"));var b=document.createEvent("MouseEvent");b.initEvent("click",!1,!1);a.dispatchEvent(b)}))})(c[a]);if(k){var e=k.offsetTop;(function(){window.onscroll=function(){k.className=this.scrollY>e?"dir_info":"fix"}})()}if(f.length)for(a=0;a<f.length;a++)(function(a){var b=
a.getAttribute("href");b&&"#"==b.substring(0,1)&&a.addEventListener("click",function(b){b.preventDefault?b.preventDefault():b.returnValue=!1;b=a.getAttribute("href");var d=document.querySelector(b).offsetTop,c=window.scrollY||document.documentElement.scrollTop,l=d>c?50:-50;clearInterval(window.inter);window.inter=setInterval(function(){window.scrollTo(0,c);c+=l;if(0<l&&c>=d||0>l&&c<=d)window.scrollTo(0,d),clearInterval(window.inter)},1)},!1)})(f[a]);if(d){var h=function(a){var c=a+d.count;if(!(c>=
b||-1>c)){var g=r[0>a?d.count:c].offsetWidth;d.left+=0>a?-g:g;d.style.marginLeft=-d.left+"px";d.count=c}},r=d.querySelectorAll(".layout > a"),b=0,c=location.href,u=!1,v=d.querySelector(".prev");v&&(d.querySelector(".prev").addEventListener("click",function(){h(-1)}),d.querySelector(".next").addEventListener("click",function(){h(1)}),d=d.querySelector(".layout"),d.left=0,d.count=-1,c=c.substring(c.lastIndexOf("/")+1),b=Number(c.substring(c.indexOf("_")+1,c.indexOf("."))),b=2);for(a=0;a<r.length;a++)(function(a){if(a){console.log(a);
var b=a.parentNode;b.addEventListener("mouseenter",function(){if("active"!=b.className){var c=document.defaultView.getComputedStyle(a,null).backgroundPosition.split(" ");c[0]="-106px";a.style.backgroundPosition=c.join(" ");b.querySelector("p").style.color="#3DB5FF"}});b.addEventListener("mouseleave",function(){if("active"!=b.className){var c=document.defaultView.getComputedStyle(a,null).backgroundPosition.split(" ");c[0]="-18px";a.style.backgroundPosition=c.join(" ");b.querySelector("p").style.color=
"#808080"}});if(!u){if("active"==b.className){var c=document.defaultView.getComputedStyle(a,null).backgroundPosition.split(" ");c[0]="-107px";a.style.backgroundPosition=c.join(" ");return u=!0}v&&h(1)}}})(r[a].querySelector("span"))}},!1);
function carousel(a){var k=document.createElement("div"),d=a.children,c=[],f=[];a.style.cssText="width: 100%; overflow: hidden; position: relative; z-index: 9";k.style.cssText="background-color: rgba(0,0,0,0.5); left: 0; bottom: 0; width: 100%; height: 25px;position: absolute; padding: 6px 20px;z-index:9999; cursor: pointer";for(var e=0;e<d.length;e++){var h=document.createElement("span");h.style.cssText="width: 12px; height: 12px; border-radius: 50%; background-color: rgba(255, 255, 255, 0.7);float: right; margin-left: 5px;";
h.index=d.length-e-1;h.addEventListener("click",function(){clearInterval(a.interval);a.increasing(this.index);a.effectShow();a.initialCarousel()});c.push(d[e]);k.appendChild(h);f.push(h)}f.reverse();d=document.createElement("span");e=document.createElement("span");d.className="last";e.className="lower";d.addEventListener("click",function(){clearInterval(a.interval);a.increasing(a.cursor-1);a.effectShow();a.initialCarousel()});e.addEventListener("click",function(){clearInterval(a.interval);a.increasing();
a.effectShow();a.initialCarousel()});a.appendChild(k);a.appendChild(d);a.appendChild(e);a.cursor=a.index=0;a.jx=!0;a.initialCarousel=function(){clearInterval(a.interval);a.interval=setInterval(function(){a.increasing();a.effectShow()},6E3)};a.increasing=function(d){a.jx&&(a.cursor=a.index,d||0==d?a.index=d:a.index++,a.index>=c.length?a.index=0:0>a.index&&(a.index=c.length-1),a.showIndex())};a.showIndex=function(){f[a.cursor].style.backgroundColor="rgba(255, 255, 255, 0.7)";f[a.index].style.backgroundColor=
"#2d3c59"};a.effectShow=function(){function d(b){b==g&&(c[a.index].className="active",c[a.cursor].className="",c[a.cursor].removeAttribute("style"),a.cursor=a.index,a.removeChild(l),a.jx=!0)}if(a.jx){a.jx=!1;var b=Math.round(4*Math.random()),e=c[a.index].offsetWidth,f=c[a.index].offsetHeight,h=c[a.index].getAttribute("src"),l=document.createElement("div"),g=0;a.appendChild(l);if(0==b){var m=[];oper=0;g=8;l.style.cssText="position: absolute; width: 100%; height: 100%; left: 0; top: 0";for(b=0;b<g;b++){var n=
document.createElement("div");n.style.cssText="position: absolute; width:100%; height: "+f/g+"px; top: "+f/g*b+"px;background: url("+h+") no-repeat 0 -"+f/g*b+"px; background-size: 100% auto;left: "+(b%2?"100%":"-100%")+";z-index:999";l.appendChild(n);m.push(n)}a.appendChild(l);for(b=0;b<m.length;b++)startMove(m[b],{left:0},function(){d(++oper)})}else if(1==b){m=[];oper=0;g=18;l.style.cssText="position: absolute; width: 100%; height: 100%; left: 0; top: 0";for(b=0;b<g;b++)n=document.createElement("div"),
n.style.cssText="position: absolute; height:100%; width: "+Math.round(e/g)+"px; left: "+e/g*b+"px;background: url("+h+") no-repeat -"+e/g*b+"px 0; background-size: auto 100%;top: "+(b%2?"100%":"-100%")+";z-index:999",l.appendChild(n),m.push(n);a.appendChild(l);for(b=0;b<m.length;b++)startMove(m[b],{top:0},function(){d(++oper)})}else if(2==b){m=[];oper=0;g=24;l.style.cssText="position: absolute; width: 100%; height: 100%; left: 0; top: 0";for(var k=0;4>k;k++)for(b=0;6>b;b++)n=document.createElement("div"),
n.style.cssText="position: absolute; height:0px; width: "+Math.round(e/6)+"px; left: "+e/6*b+"px;top: "+f/4*k+"px;opacity:0;background: url("+h+") no-repeat -"+e/6*b+"px -"+f/4*k+"px; background-size: "+e+"px "+f+"px;z-index:999",l.appendChild(n),m.push(n);a.appendChild(l);for(var p=0,t=[],b=0;b<m.length;b++)t.push(b);t.sort(function(){return Math.random()<Math.random()});(function q(){p>=m.length||(startMove(m[t[p]],{height:Math.round(f/4),opacity:100},function(){d(++oper)}),setTimeout(function(){q(++p)},
30))})()}else if(4==b){m=[];oper=0;g=18;l.style.cssText="position: absolute; width: 100%; height: 100%; left: 0; top: 0";for(b=0;b<g;b++)n=document.createElement("div"),n.style.cssText="position: absolute; height:100%; width: "+Math.round(e/g)+"px; left: "+e/g*b+"px;background: url("+h+") no-repeat -"+e/g*b+"px 0; background-size: auto 100%;top: -100%;z-index:999",l.appendChild(n),m.push(n);a.appendChild(l);p=0;(function q(){p>=m.length||(startMove(m[p],{top:0},function(){d(++oper)}),setTimeout(function(){q(++p)},
50))})()}else if(3==b){m=[];oper=0;g=6;l.style.cssText="position: absolute; width: 100%; height: 100%; left: 0; top: 0";for(b=0;b<g;b++)n=document.createElement("div"),n.style.cssText="position: absolute; height:"+Math.round(f/g)+"px; width: 100%; left: -100%;background: url("+h+") no-repeat 0 -"+f/g*b+"px; background-size: 100% auto;top: "+f/g*b+"px;z-index:999",l.appendChild(n),m.push(n);a.appendChild(l);p=0;(function q(){p>=m.length||(startMove(m[p],{left:0},function(){d(++oper)}),setTimeout(function(){q(++p)},
100))})()}}};a.showIndex();a.initialCarousel()}
function imgAsynLoad(a){function k(){var a=this.getAttribute("asyn-src"),b=this,c=new Image;c.src=a;c.onload=function(){b.setAttribute("src",a);b.removeAttribute("oper");b.removeAttribute("asyn-src");b.removeEventListener("asynload",k,!1)}}function d(){for(var a=(window.scrollY||document.documentElement.scrollTop)+window.screen.availHeight,b=0;b<c.length&&!(c[b].top>=a);b++)c[b].dom.dispatchEvent(f),c.splice(b--,1);0==c.length&&window.removeEventListener("scroll",d,!1)}a=document.querySelectorAll(a);
var c=[],f=document.createEvent("MouseEvent");f.initEvent("asynload",!1,!1);for(var e=0;e<a.length;e++){a[e].addEventListener("asynload",k,!1);var h=function b(a){return document==a?0:b(a.offsetParent||a.parentNode)+a.offsetTop}(a[e]);c.push({top:h,dom:a[e]})}c.sort(function(a,b){return a.top-b.top});window.addEventListener("scroll",d,!1);d()}function getStyle(a,k){return a.currentStyle?a.currentStyle[k]:getComputedStyle(a,!1)[k]}
function startMove(a,k,d){clearInterval(a.timer);a.timer=setInterval(function(){var c=!0,f;for(f in k){var e=0,e="opacity"==f?Math.round(100*parseFloat(getStyle(a,f))):parseInt(getStyle(a,f)),h=(k[f]-e)/6,h=0<h?Math.ceil(h):Math.floor(h);e!=k[f]&&(c=!1);"opacity"==f?(a.style.filter="alpha(opacity:"+(e+h)+")",a.style.opacity=(e+h)/100):a.style[f]=e+h+"px"}c&&(clearInterval(a.timer),d&&d())},30)};